name: qr_code_app
description: A Flutter QR Code Scanner and Generator

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.29.3'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.0
  qr_flutter: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  image_gallery_saver: ^1.7.1
  share_plus: ^7.0.0
  url_launcher: ^6.2.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  timeago: ^3.6.1
  google_mlkit_barcode_scanning: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
